export class CalenderDTO {
    draftid:number;
    User_Type:string;
    startdate:any;
    enddate:any;
    AssignedCount:any;
    location:String;
    SearchText:any;
    loc_status:Boolean;
    Schedule_type:number;
    AckDate:any;
    Emp_no:number ;
    Status_type:string;
    IsAdmin:boolean;
    Meeting_notes:any;
    Portfolio:string;
    Dms:string;
    User_list:any;
    Project:string;
    Notes:string;
    Action_item:any;
    Search_text:string;
    flag_id:number;
    propose_date:string;
    propose_stt:string;
    propose_edt:string;
    EmpNo:string;
    EventNumber:string;
    flagid:number;
    attachment:string;
    Project_Code:string;
    minutes:number;
    StartTime:string;
    EndTime:string;
    Start_date:any;
    End_date:any;
    Start_time:string;
    End_time:string;
    Status:string;
    Note:string;
    Emp_No:any;
    Weekday:string;
    json:string;
    Checkdatetimejson:string;
    Scheduled_date:string;
    AvailableSlotsJson:string;
    count:number;
    ScheduleJson:string;
    Schedule_ID:number;
    ClickEventJSON:string;
    Title:String;
    Task_Name:string;
    Scheduledsearchlist:string;
    previousmeet_data:string;
    AdminMeeting_Status:string;
    attendeesList:string;
    type:number;
    AgendaId:any;
    DraftAgendas:any;
    filterbyCompany:string;
    filterbyUser:string;
    filterbyStatus:string;
    Agendas:any;
    fileid :any;
    file_ids:any;
    Link_details:any;
    Recurrence:any;
    Rec_values:any;
    Rec_EndDate:any;
    Attendees:any;
    Pending_date:any;
    Draft_date:any;
    AttendeeCount:any;
    ProjectCount:any;
    PortfolioCount:any;
    DmsCount:any;
    Schedule_date:any;
    UserId:number;

    // Exec_BLockName:string;
    // Project_Name:string;
    // BlockNameProject:string;

}
