export class UserDTO {
  RoleId: number;
  RoleName: string;
  Password: string;
  OldPassWord: string;
  CryptedPassword: string;
  NewPassword: string;
  FirstName: string;
  LastName: string;
  Email: string;
  userId: string;
  createdby: number;
  LoginUserId: number;
  CredentialsIsValid: boolean;
  organizationid: number;
  EmployeeCode: string;
  PolicyId: number;
  PolicyHeader: string;
  PolicyContent: string;
  message: string;
  IsPolicy: boolean;
  ChryptedOldPassword: string;
  DisplayName: string;
  MiddleName: string;
  Telephone1: string;
  Telephone2: string;
  Phone: string;
  Address: string;
  DesignationName: string;
  SignatureThumbnail: string;
  City: string;
  Country: string;
  CompanyName: string;
  DepartmentName: string;
  UserName: string;
  ReportingUserName: string;
  UserDetailsJson: string;
  AgreementDate: string;
  CompanyId: number;
  DepartmentId: number;
  IsArchiveApproval: boolean;
  IsArchiveDownload: boolean;
  IsCommunicationDownload: boolean;
  UserId: Number;
  Day: string
  Signature: string
  UserProfile: string
  TourId: string
  Triggered: number
  UserIsActive: boolean;
  PinConversationCount: number;
  UserJson: string;
  CompanyJson: string;
  StatusJson: string;
  ReportingUserId: number;
  SharePopupCount: number;
}
