export class UserRegistrationDTO {

  // FirstName:string;
  // MiddleName:string;
  // lastName:string;
  // UserEmail:string;
  // Telephone1:number;
  // Telephone2:number;
  // UserPhone:number;
  // UserAddress:string;
  // Country:string;
  // UserState:string;
  //  UserCity:string;
  // UserPincode:number;

  // UserId:number;
  // OrganizationId:number;
  // // CompanyName:string;
  // CompanyId:number;

  // DepartmentId:number;
  // DepartmentName:string;
  // RoleName:string;
  // RoleId:number;
  // FlagId:number;
  // CreatedBy:number;
  // UpdatedBy:number;
  // CountryId:number;
  // CityId:number;
  // ReportingUserId:number;
  // StringEmployeeId:number;
  // EmployeeId:number;
  // ReportingUser:string;
  // DesignationId:number;
  // PositionId:number;
  // DesignationName:string;
  // IsInterCompany:boolean;
  // IsGlobalUser:boolean;
  FirstName: string;
  UserPhone: Number;
  UserName: string;
  UserEmail: string;
  MiddleName: string;
  lastName: string;

  Telephone1: number;
  Telephone2: number;
  UserAddress: string;
  CityId: number;
  CountryId: number;
  UserPincode: number;
  OrganizationId: number;
  UserIsActive: boolean;
  CreatedBy: number;
  CompanyId: number;
  DepartmentId: number;
  RoleId: number;
  FlagId: number;
  UserId: number;
  ReportingUserId: number;
  EmployeeId: number;
  DesignationId: number;
  PositionId: number;
  IsInterCompany: boolean;
  IsArchiveApproval: boolean;
  IsCommunicationDownload: boolean
  IsArchiveDownload: boolean;
  IsStreamPlannerDownload: boolean
  IsGlobalUser: boolean;
  Password: string;
  Status: boolean;
  message: string;
  Data: string;
  CountryCode: string;
  DisplayName: string;
  IsActive: boolean;
  PageNumber: Number;
  PageSize: Number;
  JSONData: string;
  ErrorMessage: string;
  Error: string;
  CompanyIds: string;
  DepartmentIds: string;
  DesignationIds: string;
  Sortby: number;
  ToUserIdsStr: string;
  IsStreamDownload: boolean
}
